### ISSUE TITLE
How to link/login to tahoma

### ISSUE THREAD

**Issue by ferdoo** [nikkow/node-red-contrib-tahoma#27] opened 2020-04-09 21:32 UTC
Hi, i try to control my tahoma window shutter from node red.
If i try to log in to my tahoma from the config node with button "Link node-red to tahoma" the login fail.
I tried to change login data in sample flow and import it but I can't select the device next.
Can someone help me successfully set up a connection to tahoma.
Thanks.

**Comment by nikkow** [comment] 2020-04-10 16:42
Hi @ferdoo,

Have you followed the guide to create the app on the Somfy Open API platform? Do you see any specific output in the node-red logs?

**Comment by Raphidev** [comment] 2020-04-15 06:46
Hello, same problem. Got error message from Somfy url after enter credentials.
Perhaps a callback url problem ? (http://127.0.0.1:1880/somfy/callback), Http server contrib needed ?

**Comment by Webunity** [comment] 2020-04-15 17:13
@nikkow same issue here; fresh install; callback URL works if i do view-source.

Somfy page shows error:
![image](https://user-images.githubusercontent.com/186093/79366829-23ea7a00-7f4d-11ea-83b7-d887322cbe1b.png)

**Comment by ferdoo** [comment] 2020-04-15 17:35
Hi, @nikkow 
Yes i have followed the guide and chcecked steps more times.
Nothing in node-red logs.
There must be some authentication problem.
By login i become same error message as @Webunity .
I noticed that when I use the Internet Explorer I can't see this tahoma node.  if I use for example chrome then this tahoma node is visible. I dont understand why ?
And I still don't know where to take io: // path / to / my / device?

**Comment by ferdoo** [comment] 2020-04-15 17:41
Callback URL: enter the URL of your node-red installation, followed by the path /somfy/callback (e.g. if installed locally: http://127.0.0.1:1880/somfy/callback).

should there not be an external ip address instead of the ip address of the node red installation?

**Comment by Webunity** [comment] 2020-04-15 17:49
Off course your callback URL should be externally reachable; it is the URL where Somfy sends your credentials towards. In my case my external URL is reachable, but Somfy is giving the auth error. I even tried to replicate the callback using the steps in the openapi-docs so i think it is not an issue on this node's end.

**Comment by ferdoo** [comment] 2020-04-15 17:57
@Webunity There can be no problem that the external ip is ipv6 ? Some internet providers use ipv6.

**Comment by ferdoo** [comment] 2020-04-15 17:59
> Off course your callback URL should be externally reachable; it is the URL where Somfy sends your credentials towards. In my case my external URL is reachable, but Somfy is giving the auth error. I even tried to replicate the callback using the steps in the openapi-docs so i think it is not an issue on this node's end.

They the port 1880 must be forwarded in router ?

**Comment by nikkow** [comment] 2020-04-15 18:02
> Callback URL: enter the URL of your node-red installation, followed by the path /somfy/callback (e.g. if installed locally: http://127.0.0.1:1880/somfy/callback).
> 
> should there not be an external ip address instead of the ip address of the node red installation?

Not necessarily. Somfy will not send anything directly to this address (no server-to-server request), but will redirect your browser to your callback, with a token as a query parameter. I will perform a fresh install on a new machine right away and let you know if I can reproduce.

**Comment by nikkow** [comment] 2020-04-15 18:07
@ferdoo can you please try the following? 

1. Login to Somfy Open API developer platform (https://developer.somfy.com/)
2. Try executing one of the example calls (e.g. https://developer.somfy.com/somfy-open-api/apis/get/site)

You will need to click on the "OAuth 2.0 Set..." button that will open a popup prompting for your credentials. 

I have just tried this issue and cannot login, I receive an _access token negociation_ error systematically.

**Comment by ferdoo** [comment] 2020-04-15 18:13
> @ferdoo can you please try the following?
> 
> 1. Login to Somfy Open API developer platform (https://developer.somfy.com/)
> 2. Try executing one of the example calls (e.g. https://developer.somfy.com/somfy-open-api/apis/get/site)
> 
> You will need to click on the "OAuth 2.0 Set..." button that will open a popup prompting for your credentials.
> 
> I have just tried this issue and cannot login, I receive an _access token negociation_ error systematically.
> 
> Update: I have sent an email to Somfy Developer Support. I am now waiting for their feedback.

I becomme this :
Error: access_token negotiation failure

**Comment by nikkow** [comment] 2020-04-15 18:14
OK, we face the same issue. I have reported this to the Somfy Devleopment Team, there is not much I can do on my end. We'll have to wait for their answer :)

**Comment by ferdoo** [comment] 2020-04-15 18:19
> OK, we face the same issue. I have reported this to the Somfy Devleopment Team, there is not much I can do on my end. We'll have to wait for their answer :)

thank you, we moved a little :)
please let know if you have some info

**Comment by nikkow** [comment] 2020-04-15 18:20
I will update this issue as soon as I receive a feedback 🙂

**Comment by miro0278** [comment] 2020-04-15 21:04
I have the same issue like ferdoo

**Comment by Webunity** [comment] 2020-04-16 09:05
Thank you @nikkow for your investigations on this :)

**Comment by frankis78** [comment] 2020-04-27 19:01
I also face the same issue. Hope Somfy will fix it:)

**Comment by frankis78** [comment] 2020-04-29 08:40
I was been able to workaround it by putting different Callback URL (generated from https://webhook.site/) in Somfy developer app settings. Then I get back to my Node Red installation and oauth authentication ran without any problems and gave me the correct access & refresh tokens.  Communication with Tahoma Hub is working now.
I think something is wrong with callback URL set on the somfy settings. With the right callback url where my node-red is running (http://node-red-ip:1880/somfy/callback) it was giving me ´´{"error":"redirect_uri_mismatch","error_description":"The redirect URI provided does not match registered URI(s)."}´. But as soon as I set different URL at the somfy website, I was been able to authenticate from node red.

**Comment by Webunity** [comment] 2020-04-29 20:14
Any updates because this is blocking my integration...

**Comment by nikkow** [comment] 2020-05-02 17:46
I haven't heard back from Somfy since my last e-mail. I just tried to login through their documentation samples and it seems to be back online. Can you please try the procedure mentioned in [this comment](https://github.com/nikkow/node-red-contrib-tahoma/issues/27#issuecomment-614193919)?

Regarding the callback issue, my setup skips the `/somfy/callback` bit and manages to login just fine. I tried to reproduce and created a new node-red instance on the LAN (using its local IP as the host and the default port). When creating the app on Somfy portal, I just set `http://192.168.x.y:1880/` as the callback URL, wait a few minutes for it to be activated (~10 min. after seeing the "Approved" badge). I then setup the node using the API key/secret provided and it logged just fine. 

@frankis78 can you please provide more details about your config (without any private/sensitive info) to better understand the issue you are facing? 

Thanks

**Comment by Raphidev** [comment] 2020-05-03 09:45
I just checked out the workaround from #frankis78, with no success. As #nikkow says, try to remove /somfy/callback in url didn't work.
There is still a issue with de somfy server.
I have read that somfy API isn't available in all countries, so check country in your somfy dev account. In my case it was set by default in afghanistan. I managed to change that.

**Comment by nikkow** [comment] 2020-05-03 13:05
Hi @Raphidev, did it work after changing the default country?

**Comment by frankis78** [comment] 2020-05-06 17:16
When i first experienced this issue, then i had the local ip in the node-red settings.
And i couldnt refresh the tokens.
But after i changed to a different external webhook, i was able to get the correct tokens in node-red.

![2020-05-06_1911](https://user-images.githubusercontent.com/26933092/81207522-f766d280-8fcd-11ea-843f-d5ed5baa28f4.png)
![2020-05-06_1909](https://user-images.githubusercontent.com/26933092/81207527-f9309600-8fcd-11ea-865c-24bb9736ff57.png)

I have now tried to set back the local Ip adress in the app settings of somfy, to see it will still work.

**Comment by risa** [comment] 2020-06-15 20:17
Hi, I am also trying hard to generate the access_token but without success. 

I have even tried to generate the access_code  using the Somfy description of the OAuth2 protocol, but event then I did not succeed. 

I have tried to change the country as @Raphidev suggested but without success. 

I can authorise using the APIs Documentation and test the calls just fine. Using this I can also extract the access token from the Bearer header from the CURL representation. 

@nikkow is it possible to inject the access_token straight into your module bypassing the OAuth2 authorisation flow? It seems that there must be something broken on the Somfy side with the application approvals or something. With direct injection, it would be possible to start working now as a temporary hack. 

Thanks!

**Comment by tomy-d** [comment] 2020-07-23 15:38
Hi, I do have the same issue. 
One question according the installation:
When you are saying that I have to enter the path for the local installation :e.g. http://127.0.0.1:1880/somfy/callback running node ed o a raspy ... is it important where the node is installed exactly on my raspy? I mean do I have to look for in which path nedered and the somfy node has been installed???

**Comment by nikkow** [comment] 2020-07-24 15:24
Hi @risa,

It is actually not possible to inject the token directly from the config node, I will create a task to add those fields. It won't hurt to at least make them editable. We also have to keep in mind that the access token is short-lived. During my tests, it was only valid for an hour. 

@tomy-d: actually the only elements that matter are the IP and port on which your node-red instance is installed. The `/somfy/callback` bit is a route created by the node itself.

**Comment by Raphidev** [comment] 2020-08-03 20:08
Still malfunction.
I tried with HomeAssit and it works, so i think it is not a Somfy related issue problem.

**Comment by hmwelsch** [comment] 2020-08-17 15:39
Hi, I have worked on this again today as well. I have tried to build the calls outside of Node-Red and get persistently the same results too. I have now also tried to contact Somfy (Germany) and hope for some response from there.

**Comment by tomy-d** [comment] 2020-08-17 16:28
@hmwelsch have tried several times to contact somfy support...they never replied...really poor service!

**Comment by jaerc** [comment] 2020-08-24 19:24
> I will update this issue as soon as I receive a feedback 🙂

**Comment by jaerc** [comment] 2020-08-24 19:30
Hi nikkow
I have the same error message if I try the Link Node-Red to Tahoma button. 

The link on the page with the error message looks like this: https://accounts.somfy.com/oauth/oauth/v2/auth?response_type=code&client_id=xYW2w32OQBSYxGFFGCYvBUQE8ME1HNt4MtVdr_HBucX5tp4jcmUwJUN9M2vwByN5P1BO0ULVvHh8r9Hb1UJrO8JT&redirect_uri=http://myexternalnasurl:1880/somfy/callback&state=setup&grant_type=authorization_code

As callback url I did configure:   http://myexternalnasurl:1880/somfy/callback 

Oauth2 is authenticated on the somfy page and if I try it out the response is OK.  So this authentication works on my site, but I still get the same error message.

Is there anything else I can try?

**Comment by nikkow** [comment] 2020-08-25 17:24
Hi @jaerc,

There seems to be a bug when registering callbacks on Somfy's developer portal (see #39). The only workaround for now is to contact them, so they can manually fix the affected callback in their database, hoping that they'll fix their workflow quickly.

**Comment by nikkow** [comment] 2020-08-25 17:24
Since they were several login-related issues discussed in this thread, I'll keep #39 open to discuss the callback issue. The other login problems were fixed in the latest releases.

Thanks!

**Closed by nikkow** 2020-08-25 17:24 UTC
Labels: Somfy Issue, bug
